# Generated by Django 3.1.4 on 2021-01-28 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 9, 58, 2, 348823)),
        ),
    ]
