# Generated by Django 3.1.4 on 2021-01-29 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipkart',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 8, 19, 36, 986626)),
        ),
    ]
